# Generated by Django 2.1.5 on 2019-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('wiki', '0001_initial'), ('wiki', '0002_auto_20190106_1617')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(to='wiki.Tag'),
        ),
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
