# Generated by Django 2.1.5 on 2019-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
